name: generate cp stats png

on:
  schedule:
    - cron: "0 */1 * * *" # Run every hour
  workflow_dispatch:

jobs:
  generate-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install wkhtmltoimage
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wkhtmltopdf

      - name: Create Output Directory
        run: |
          mkdir -p output  # Use -p to avoid errors if the directory already exists

      - name: Install ImageMagick
        run: sudo apt-get install -y imagemagick
      
      - name: Generate Codeforces Image
        run: wkhtmltoimage --javascript-delay 10000 https://codeforces-readme-stats.vercel.app/api/card?username=shankarlohar output/codeforces_generated.png
      
      - name: Trim Codeforces Image
        run: convert output/codeforces_generated.png -trim output/codeforces_generated_trimmed.png
      
      - name: Sleep for some time
        run: sleep 10s
      
      - name: Generate Leetcode Image
        run: wkhtmltoimage --javascript-delay 10000 https://leetcard.jacoblin.cool/shankarlohar?theme=light output/leetcode_generated.png
      
      - name: Trim Leetcode Image
        run: convert output/leetcode_generated.png -trim output/leetcode_generated_trimmed.png


      - name: Push to image-output branch
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: cp-stats
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.CP_TOKEN }}
