name: Generate Image

on:
  schedule:
    - cron: "0 */1 * * *" # every 1 hours

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
      
    - name: Install dependencies
      run: npm install puppeteer

    - name: Generate Image
      run: node generate-image.js

    - name: Checkout to image-output branch
      run: git checkout -B image-output
      
    - name: Commit and Push
      run: |
        git config user.name 'shankarlohar'
        git config user.email 'shankarloharmail@gmail.com'
        git add -A
        git commit -m "Generate new image"
        git push origin image-output --force
