name: Generate Image

on:
  schedule:
    - cron: "0 */1 * * *" # Run every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install wkhtmltoimage
      run: |
        sudo apt-get update -y
        sudo apt-get install -y wkhtmltopdf

    - name: Generate Image
      run: |
        wkhtmltoimage https://codeforces-readme-stats.vercel.app/api/card?username=shankarlohar generated_image.png

    - name: Checkout to image-output branch
      run: git checkout -B image-output

    - name: Commit and Push
      run: |
        git config user.name 'shankarlohar'
        git config user.email 'shankarloharmail@gmail.com'
        git add -A
        git commit -m "Generated new image"
        git push --set-upstream https://${{ secrets.CODEFORCES_TOKEN }}@github.com/shankarlohar/codeforces.git image-output --force
      env:
        CODEFORCES_TOKEN: ${{ secrets.CODEFORCES_TOKEN }}
