name: Generate Image and Push to Branch

on:
  schedule:
    - cron: "0 */1 * * *" # Run every hour
  workflow_dispatch:

jobs:
  generate-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install wkhtmltoimage
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wkhtmltopdf

      - name: Generate Image
        run: |
          mkdir output
          wkhtmltoimage https://codeforces-readme-stats.vercel.app/api/card?username=shankarlohar output/generated_image.png

      - name: Push to image-output branch
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: image-output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.CODEFORCES_TOKEN }}
