name: Generate Image and Push to Branch

on:
  schedule:
    - cron: "0 */1 * * *" # Run every hour
  workflow_dispatch:

jobs:
  generate-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install wkhtmltoimage
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wkhtmltopdf

      - name: Create Output Directory
        run: |
          mkdir -p output  # Use -p to avoid errors if the directory already exists

      - name: Generate Codeforces Image
        run: |
          wkhtmltoimage --javascript-delay 10000 https://codeforces-readme-stats.vercel.app/api/card?username=shankarlohar output/codeforces_generated.png

      - name: Sleep for some time
        run: sleep 10s

      - name: Generate Leetcode PDF
        run: |  
          wkhtmltopdf --javascript-delay 10000 https://leetcard.jacoblin.cool/shankarlohar?ext=contest&theme=light output/leetcode_generated.pdf

      - name: Install pdf utilities
        run: |
          sudo apt-get update -y
          sudo apt-get install -y poppler-utils

      - name: Convert PDF to PNG
        run: |
          pdftoppm -png output/leetcode_generated.pdf output/leetcode_generated

      - name: Push to image-output branch
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: image-output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.CODEFORCES_TOKEN }}
